pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/angelhumera/shopping_login.git '
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t shopping-login-app .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8081:80 shopping-login-app'
            }
        }
    }
}
